name: AWS CodeGuru Reviewer

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  codeguru-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for CodeGuru Reviewer to access full repository history

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run AWS CodeGuru Reviewer
        uses: aws/codeguru-reviewer-action@v1.0.4
        with:
          build-path: './' # Path to the build artifacts or root of the repository
