name: AWS CodeGuru Reviewer

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  codeguru-reviewer:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for CodeGuru Reviewer

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Add CodeGuru Reviewer Action
      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          build_path: . # Update if your build artifacts are located in a different directory
          s3_bucket: codeguru-reviewer-myactions-bucket10 # Your S3 bucket with "codeguru-reviewer-*" prefix

      # Step 4: Upload results into GitHub
      - name: Upload review result
        if: ${{ github.event_name != 'push' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeguru-results.sarif.json
